name: Test Scripts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test setup script syntax
      run: |
        Get-Content setup.bat | ForEach-Object {
          if ($_ -match "@echo off|echo|set|if|goto|call|pause|exit") {
            Write-Host "✓ Valid batch command: $_"
          }
        }
      shell: powershell

    - name: Validate JSON configs
      run: |
        Get-ChildItem -Path "workspaces/*.json" | ForEach-Object {
          try {
            Get-Content $_.FullName | ConvertFrom-Json | Out-Null
            Write-Host "✓ Valid JSON: $($_.Name)"
          } catch {
            Write-Error "✗ Invalid JSON: $($_.Name)"
            exit 1
          }
        }
      shell: powershell

    - name: Test devcontainer config
      run: |
        try {
          Get-Content ".devcontainer/devcontainer.json" | ConvertFrom-Json | Out-Null
          Write-Host "✓ Valid devcontainer.json"
        } catch {
          Write-Error "✗ Invalid devcontainer.json"
          exit 1
        }
      shell: powershell